//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 11:24:45 AM CET 
//


package files.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RECHNUNG" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UNTERNEHMEN">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UMSATZSTEUER_IDENTIFIKATIONSNUMMER" type="{}USIN"/>
 *                             &lt;element name="TELEPHONE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LEISTUNGSEMPFAENGER">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ANREDE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="VOLLST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AUSSTELLUNGSDATUM" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="RECHNUNGSNUMMER" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="LEISTUNGEN">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LEISTUNG" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MENGE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="EINHEIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PRODUKT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="EINZELPREIS" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                       &lt;element name="GESAMTPREIS" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="MWST" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ENTGELD">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RECHNUNGSBETRAG" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="NETTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="MWST" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ZAHLUNGSMOEGLICHKEITEN">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BANK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="KONTONUMMER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="IBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="BITCOIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rechnung"
})
@XmlRootElement(name = "RECHNUNGEN")
public class RECHNUNGEN {

    @XmlElement(name = "RECHNUNG", required = true)
    protected List<RECHNUNGEN.RECHNUNG> rechnung;

    /**
     * Gets the value of the rechnung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rechnung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRECHNUNG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RECHNUNGEN.RECHNUNG }
     * 
     * 
     */
    public List<RECHNUNGEN.RECHNUNG> getRECHNUNG() {
        if (rechnung == null) {
            rechnung = new ArrayList<RECHNUNGEN.RECHNUNG>();
        }
        return this.rechnung;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UNTERNEHMEN">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UMSATZSTEUER_IDENTIFIKATIONSNUMMER" type="{}USIN"/>
     *                   &lt;element name="TELEPHONE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LEISTUNGSEMPFAENGER">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ANREDE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="VOLLST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AUSSTELLUNGSDATUM" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="RECHNUNGSNUMMER" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="LEISTUNGEN">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LEISTUNG" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="MENGE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="EINHEIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PRODUKT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EINZELPREIS" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                             &lt;element name="GESAMTPREIS" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="MWST" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ENTGELD">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RECHNUNGSBETRAG" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="NETTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="MWST" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ZAHLUNGSMOEGLICHKEITEN">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BANK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="KONTONUMMER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="IBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="BITCOIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unternehmen",
        "leistungsempfaenger",
        "ausstellungsdatum",
        "rechnungsnummer",
        "leistungen",
        "entgeld",
        "zahlungsmoeglichkeiten"
    })
    public static class RECHNUNG {

        @XmlElement(name = "UNTERNEHMEN", required = true)
        protected RECHNUNGEN.RECHNUNG.UNTERNEHMEN unternehmen;
        @XmlElement(name = "LEISTUNGSEMPFAENGER", required = true)
        protected RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER leistungsempfaenger;
        @XmlElement(name = "AUSSTELLUNGSDATUM", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar ausstellungsdatum;
        @XmlElement(name = "RECHNUNGSNUMMER", required = true)
        protected BigDecimal rechnungsnummer;
        @XmlElement(name = "LEISTUNGEN", required = true)
        protected RECHNUNGEN.RECHNUNG.LEISTUNGEN leistungen;
        @XmlElement(name = "ENTGELD", required = true)
        protected RECHNUNGEN.RECHNUNG.ENTGELD entgeld;
        @XmlElement(name = "ZAHLUNGSMOEGLICHKEITEN", required = true)
        protected RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN zahlungsmoeglichkeiten;

        /**
         * Gets the value of the unternehmen property.
         * 
         * @return
         *     possible object is
         *     {@link RECHNUNGEN.RECHNUNG.UNTERNEHMEN }
         *     
         */
        public RECHNUNGEN.RECHNUNG.UNTERNEHMEN getUNTERNEHMEN() {
            return unternehmen;
        }

        /**
         * Sets the value of the unternehmen property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECHNUNGEN.RECHNUNG.UNTERNEHMEN }
         *     
         */
        public void setUNTERNEHMEN(RECHNUNGEN.RECHNUNG.UNTERNEHMEN value) {
            this.unternehmen = value;
        }

        /**
         * Gets the value of the leistungsempfaenger property.
         * 
         * @return
         *     possible object is
         *     {@link RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER }
         *     
         */
        public RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER getLEISTUNGSEMPFAENGER() {
            return leistungsempfaenger;
        }

        /**
         * Sets the value of the leistungsempfaenger property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER }
         *     
         */
        public void setLEISTUNGSEMPFAENGER(RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER value) {
            this.leistungsempfaenger = value;
        }

        /**
         * Gets the value of the ausstellungsdatum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAUSSTELLUNGSDATUM() {
            return ausstellungsdatum;
        }

        /**
         * Sets the value of the ausstellungsdatum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAUSSTELLUNGSDATUM(XMLGregorianCalendar value) {
            this.ausstellungsdatum = value;
        }

        /**
         * Gets the value of the rechnungsnummer property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRECHNUNGSNUMMER() {
            return rechnungsnummer;
        }

        /**
         * Sets the value of the rechnungsnummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRECHNUNGSNUMMER(BigDecimal value) {
            this.rechnungsnummer = value;
        }

        /**
         * Gets the value of the leistungen property.
         * 
         * @return
         *     possible object is
         *     {@link RECHNUNGEN.RECHNUNG.LEISTUNGEN }
         *     
         */
        public RECHNUNGEN.RECHNUNG.LEISTUNGEN getLEISTUNGEN() {
            return leistungen;
        }

        /**
         * Sets the value of the leistungen property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECHNUNGEN.RECHNUNG.LEISTUNGEN }
         *     
         */
        public void setLEISTUNGEN(RECHNUNGEN.RECHNUNG.LEISTUNGEN value) {
            this.leistungen = value;
        }

        /**
         * Gets the value of the entgeld property.
         * 
         * @return
         *     possible object is
         *     {@link RECHNUNGEN.RECHNUNG.ENTGELD }
         *     
         */
        public RECHNUNGEN.RECHNUNG.ENTGELD getENTGELD() {
            return entgeld;
        }

        /**
         * Sets the value of the entgeld property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECHNUNGEN.RECHNUNG.ENTGELD }
         *     
         */
        public void setENTGELD(RECHNUNGEN.RECHNUNG.ENTGELD value) {
            this.entgeld = value;
        }

        /**
         * Gets the value of the zahlungsmoeglichkeiten property.
         * 
         * @return
         *     possible object is
         *     {@link RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN }
         *     
         */
        public RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN getZAHLUNGSMOEGLICHKEITEN() {
            return zahlungsmoeglichkeiten;
        }

        /**
         * Sets the value of the zahlungsmoeglichkeiten property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN }
         *     
         */
        public void setZAHLUNGSMOEGLICHKEITEN(RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN value) {
            this.zahlungsmoeglichkeiten = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RECHNUNGSBETRAG" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="NETTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="MWST" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rechnungsbetrag",
            "netto",
            "mwst"
        })
        public static class ENTGELD {

            @XmlElement(name = "RECHNUNGSBETRAG")
            protected double rechnungsbetrag;
            @XmlElement(name = "NETTO")
            protected double netto;
            @XmlElement(name = "MWST")
            protected double mwst;

            /**
             * Gets the value of the rechnungsbetrag property.
             * 
             */
            public double getRECHNUNGSBETRAG() {
                return rechnungsbetrag;
            }

            /**
             * Sets the value of the rechnungsbetrag property.
             * 
             */
            public void setRECHNUNGSBETRAG(double value) {
                this.rechnungsbetrag = value;
            }

            /**
             * Gets the value of the netto property.
             * 
             */
            public double getNETTO() {
                return netto;
            }

            /**
             * Sets the value of the netto property.
             * 
             */
            public void setNETTO(double value) {
                this.netto = value;
            }

            /**
             * Gets the value of the mwst property.
             * 
             */
            public double getMWST() {
                return mwst;
            }

            /**
             * Sets the value of the mwst property.
             * 
             */
            public void setMWST(double value) {
                this.mwst = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LEISTUNG" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="MENGE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="EINHEIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PRODUKT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EINZELPREIS" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                   &lt;element name="GESAMTPREIS" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="MWST" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "leistung"
        })
        public static class LEISTUNGEN {

            @XmlElement(name = "LEISTUNG", required = true)
            protected List<RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG> leistung;

            /**
             * Gets the value of the leistung property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the leistung property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLEISTUNG().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG }
             * 
             * 
             */
            public List<RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG> getLEISTUNG() {
                if (leistung == null) {
                    leistung = new ArrayList<RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG>();
                }
                return this.leistung;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="MENGE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="EINHEIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PRODUKT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EINZELPREIS" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *         &lt;element name="GESAMTPREIS" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *       &lt;/sequence>
             *       &lt;attribute name="MWST" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "menge",
                "einheit",
                "produkt",
                "einzelpreis",
                "gesamtpreis"
            })
            public static class LEISTUNG {

                @XmlElement(name = "MENGE", required = true)
                protected BigDecimal menge;
                @XmlElement(name = "EINHEIT", required = true)
                protected String einheit;
                @XmlElement(name = "PRODUKT", required = true)
                protected String produkt;
                @XmlElement(name = "EINZELPREIS")
                protected Double einzelpreis;
                @XmlElement(name = "GESAMTPREIS")
                protected double gesamtpreis;
                @XmlAttribute(name = "MWST")
                protected BigDecimal mwst;

                /**
                 * Gets the value of the menge property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getMENGE() {
                    return menge;
                }

                /**
                 * Sets the value of the menge property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setMENGE(BigDecimal value) {
                    this.menge = value;
                }

                /**
                 * Gets the value of the einheit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEINHEIT() {
                    return einheit;
                }

                /**
                 * Sets the value of the einheit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEINHEIT(String value) {
                    this.einheit = value;
                }

                /**
                 * Gets the value of the produkt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPRODUKT() {
                    return produkt;
                }

                /**
                 * Sets the value of the produkt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPRODUKT(String value) {
                    this.produkt = value;
                }

                /**
                 * Gets the value of the einzelpreis property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getEINZELPREIS() {
                    return einzelpreis;
                }

                /**
                 * Sets the value of the einzelpreis property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setEINZELPREIS(Double value) {
                    this.einzelpreis = value;
                }

                /**
                 * Gets the value of the gesamtpreis property.
                 * 
                 */
                public double getGESAMTPREIS() {
                    return gesamtpreis;
                }

                /**
                 * Sets the value of the gesamtpreis property.
                 * 
                 */
                public void setGESAMTPREIS(double value) {
                    this.gesamtpreis = value;
                }

                /**
                 * Gets the value of the mwst property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getMWST() {
                    return mwst;
                }

                /**
                 * Sets the value of the mwst property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setMWST(BigDecimal value) {
                    this.mwst = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ANREDE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="VOLLST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "anrede",
            "vollstname",
            "anschrift"
        })
        public static class LEISTUNGSEMPFAENGER {

            @XmlElement(name = "ANREDE")
            protected String anrede;
            @XmlElement(name = "VOLLST_NAME", required = true)
            protected String vollstname;
            @XmlElement(name = "ANSCHRIFT", required = true)
            protected String anschrift;

            /**
             * Gets the value of the anrede property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getANREDE() {
                return anrede;
            }

            /**
             * Sets the value of the anrede property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setANREDE(String value) {
                this.anrede = value;
            }

            /**
             * Gets the value of the vollstname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVOLLSTNAME() {
                return vollstname;
            }

            /**
             * Sets the value of the vollstname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVOLLSTNAME(String value) {
                this.vollstname = value;
            }

            /**
             * Gets the value of the anschrift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getANSCHRIFT() {
                return anschrift;
            }

            /**
             * Sets the value of the anschrift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setANSCHRIFT(String value) {
                this.anschrift = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ANSCHRIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UMSATZSTEUER_IDENTIFIKATIONSNUMMER" type="{}USIN"/>
         *         &lt;element name="TELEPHONE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "anschrift",
            "umsatzsteueridentifikationsnummer",
            "telephone"
        })
        public static class UNTERNEHMEN {

            @XmlElement(name = "NAME", required = true)
            protected String name;
            @XmlElement(name = "ANSCHRIFT", required = true)
            protected String anschrift;
            @XmlElement(name = "UMSATZSTEUER_IDENTIFIKATIONSNUMMER", required = true)
            protected String umsatzsteueridentifikationsnummer;
            @XmlElement(name = "TELEPHONE", required = true)
            protected BigDecimal telephone;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNAME() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNAME(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the anschrift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getANSCHRIFT() {
                return anschrift;
            }

            /**
             * Sets the value of the anschrift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setANSCHRIFT(String value) {
                this.anschrift = value;
            }

            /**
             * Gets the value of the umsatzsteueridentifikationsnummer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUMSATZSTEUERIDENTIFIKATIONSNUMMER() {
                return umsatzsteueridentifikationsnummer;
            }

            /**
             * Sets the value of the umsatzsteueridentifikationsnummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUMSATZSTEUERIDENTIFIKATIONSNUMMER(String value) {
                this.umsatzsteueridentifikationsnummer = value;
            }

            /**
             * Gets the value of the telephone property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTELEPHONE() {
                return telephone;
            }

            /**
             * Sets the value of the telephone property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTELEPHONE(BigDecimal value) {
                this.telephone = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BANK" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="KONTONUMMER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="IBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="BITCOIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bank",
            "kontonummer",
            "iban",
            "bic",
            "bitcoin"
        })
        public static class ZAHLUNGSMOEGLICHKEITEN {

            @XmlElement(name = "BANK", required = true)
            protected String bank;
            @XmlElement(name = "KONTONUMMER")
            protected BigDecimal kontonummer;
            @XmlElement(name = "IBAN")
            protected String iban;
            @XmlElement(name = "BIC")
            protected String bic;
            @XmlElement(name = "BITCOIN")
            protected String bitcoin;

            /**
             * Gets the value of the bank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBANK() {
                return bank;
            }

            /**
             * Sets the value of the bank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBANK(String value) {
                this.bank = value;
            }

            /**
             * Gets the value of the kontonummer property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getKONTONUMMER() {
                return kontonummer;
            }

            /**
             * Sets the value of the kontonummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setKONTONUMMER(BigDecimal value) {
                this.kontonummer = value;
            }

            /**
             * Gets the value of the iban property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIBAN() {
                return iban;
            }

            /**
             * Sets the value of the iban property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIBAN(String value) {
                this.iban = value;
            }

            /**
             * Gets the value of the bic property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBIC() {
                return bic;
            }

            /**
             * Sets the value of the bic property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBIC(String value) {
                this.bic = value;
            }

            /**
             * Gets the value of the bitcoin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBITCOIN() {
                return bitcoin;
            }

            /**
             * Sets the value of the bitcoin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBITCOIN(String value) {
                this.bitcoin = value;
            }

        }

    }

}
