//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.27 at 11:16:24 PM CET 
//


package namensraum.mein;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the namensraum.mein package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: namensraum.mein
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RECHNUNGEN }
     * 
     */
    public RECHNUNGEN createRECHNUNGEN() {
        return new RECHNUNGEN();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG }
     * 
     */
    public RECHNUNGEN.RECHNUNG createRECHNUNGENRECHNUNG() {
        return new RECHNUNGEN.RECHNUNG();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.LEISTUNGEN }
     * 
     */
    public RECHNUNGEN.RECHNUNG.LEISTUNGEN createRECHNUNGENRECHNUNGLEISTUNGEN() {
        return new RECHNUNGEN.RECHNUNG.LEISTUNGEN();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.UNTERNEHMEN }
     * 
     */
    public RECHNUNGEN.RECHNUNG.UNTERNEHMEN createRECHNUNGENRECHNUNGUNTERNEHMEN() {
        return new RECHNUNGEN.RECHNUNG.UNTERNEHMEN();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER }
     * 
     */
    public RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER createRECHNUNGENRECHNUNGLEISTUNGSEMPFAENGER() {
        return new RECHNUNGEN.RECHNUNG.LEISTUNGSEMPFAENGER();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.ENTGELD }
     * 
     */
    public RECHNUNGEN.RECHNUNG.ENTGELD createRECHNUNGENRECHNUNGENTGELD() {
        return new RECHNUNGEN.RECHNUNG.ENTGELD();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN }
     * 
     */
    public RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN createRECHNUNGENRECHNUNGZAHLUNGSMOEGLICHKEITEN() {
        return new RECHNUNGEN.RECHNUNG.ZAHLUNGSMOEGLICHKEITEN();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.Ausstellung }
     * 
     */
    public RECHNUNGEN.RECHNUNG.Ausstellung createRECHNUNGENRECHNUNGAusstellung() {
        return new RECHNUNGEN.RECHNUNG.Ausstellung();
    }

    /**
     * Create an instance of {@link RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG }
     * 
     */
    public RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG createRECHNUNGENRECHNUNGLEISTUNGENLEISTUNG() {
        return new RECHNUNGEN.RECHNUNG.LEISTUNGEN.LEISTUNG();
    }

}
